[versions]
kotlin = "2.4.10"
loom = "1.17-SNAPSHOT"
fabric-loader = "0.19.3"
fabric-kotlin-loader = "1.13.13+kotlin.2.4.10"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }

[libraries]
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-kotlin-loader = { group = "net.fabricmc", name = "fabric-language-kotlin", version.ref = "fabric-kotlin-loader" }